$:
  vscode:
    - services:
        - vscode
        - docker
      docker:
        image: docker.cnb.cool/flyinbug/dev-ops/nodejs:latest
      stages:
        - name: 安装依赖
          script: yarn
main:
  push:
    - name: "向量化数据"
      stages:
        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            include: "**/**.md"
    - name: "推送镜像"
      imports:
        - https://cnb.cool/Mintimate/secret/-/blob/main/SyncToGitHub.yml
      stages:
        - name: 自动同步代码
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/Mintimate/vector-mcp-edge.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}
            branch: main
            force: true
    - name: "构建产物"
      imports:
        - https://cnb.cool/Mintimate/secret/-/blob/main/DocVitePressOMR.yaml
      docker:        
        image: node:22
        volumes:
          - /root/.npm:copy-on-write
          - node_modules:copy-on-write
      stages:
        - name: "部署流程"
          image: tencentcom/deploy-eopages:latest
          script: 
            - apk add --no-cache git
            - edgeone pages deploy -n vector-mcp-edge -t $EO_SECRET
