include:
  - .cnb/pipeline/knowledge-base.yml
  - .cnb/pipeline/sync-github.yml
  - .cnb/pipeline/deploy-edgeone.yml

$:
  vscode:
    services:
      - vscode
      - docker
    docker:
      image: docker.cnb.cool/flyinbug/dev-ops/nodejs:latest
    stages:
      - name: 安装依赖
        script: yarn
